### ISSUE TITLE
某些平台下不能完全适配

### ISSUE THREAD

**Issue by Holly-szy** [EurekaScratch/eureka#38]
在Mind+（[https://ide.mindplus.top/](https://ide.mindplus.top/)）中加载“白猫的输入框”扩展时，左边的积木会全部挤在一起。  
![如图所示](https://github.com/EurekaScratch/eureka/assets/117550933/c30c368c-fe03-4e7d-a6ff-ca00c7a80879)

**Comment by SimonShiki** [comment]
无法复现，请附带报错

**Comment by The11thPencil** [comment]
incompatibility is expected tbh

**Comment by FurryR** [comment]
Mind+ 不是现代 Scratch 分支，它使用了极为早期的 Scratch 版本，不支持 LABEL 相关的标签，对于很多扩展积木的解析也存在问题。
将延后考虑对此平台的支持。

---

备注：
错误信息：

```
Error parsing block:
{
  "block": {
    "blockType": "label",
    "terminal": false,
    "blockAllThreads": false,
    "arguments": {},
    "text": "输入框"
  },
  "error": {
    "message": "Cannot read properties of undefined (reading 'type')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'type')\n    at t.value (https://ide.mindplus.top/chunks/08409de6839ab9f27a75.gui.1.6.5.js:1:940344)\n    at t.value (https://ide.mindplus.top/chunks/08409de6839ab9f27a75.gui.1.6.5.js:1:937870)\n    at r.value (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Eureka.user.js&id=acd47260-1493-4db2-abfd-486d081eb650:37:74458)\n    at or.value.rr.mark.rr.wrap.t.extensions.register (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Eureka.user.js&id=acd47260-1493-4db2-abfd-486d081eb650:37:72562)\n    at Object.set (blob:https://ide.mindplus.top/d9feaed9-0c01-418f-99f0-b481b6d1a95c:91:30)\n    at blob:https://ide.mindplus.top/9ac31ab0-0283-4336-892a-d03abe897a7b:1575:16\n    at blob:https://ide.mindplus.top/9ac31ab0-0283-4336-892a-d03abe897a7b:1599:3"
  }
}

at
value @ 08409de….gui.1.6.5.js:1

value @ 08409de….gui.1.6.5.js:1
value @ userscript.html?name…bfd-486d081eb650:37
or.value.rr.mark.rr.wrap.t.extensions.register @ userscript.html?name…bfd-486d081eb650:37
set @ d9feaed9-0c01-418f-99f0-b481b6d1a95c:91
(匿名) @ 9ac31ab0-0283-4336-8…a-d03abe897a7b:1575
(匿名) @ 9ac31ab0-0283-4336-8…a-d03abe897a7b:1599
```
